version: "3.8"

services:
  github-runner-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-runner:latest
    container_name: github-runner-frontend
    restart: unless-stopped
    env_file:
      - .env-frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-work-frontend:/home/runner/_work

volumes:
  runner-work-frontend:
